### ISSUE TITLE
Orbit/follow state not cleared properly

### ISSUE THREAD

**Issue by avosirenfal** [ColonialMarines-Mirror/ColonialMarines-2018#110]
I'm not sure how to reproduce this, but I have a video of the issue. When it happens your camera will keep teleporting between every person (or alien) you've tried to observe every few seconds.

What I know:

- I reconnected at least once while observing earlier in the round. That may be related, I'm not sure.
- Restarting the game does not fix it.
- Moving as a ghost does not fix it.
- If you accept a larva your camera will not be broken in-game. I'm still playing the round so I'm not sure if observing after dying will be broken or not. I'll edit this if that happens.

Video here: https://www.youtube.com/watch?v=LBEt1mpGnqg

**Comment by Jared-Fogle** [comment]
My fault entirely, working on it.
