### ISSUE TITLE
Vents aren't visible to aliens ventcrawling

### ISSUE THREAD

**Issue by avosirenfal** [ColonialMarines-Mirror/ColonialMarines-2018#119]
This is very painful for aliens. Example image: There's a straight line of vents here that's unbroken, I'm crawling in them but they're not visible.

![image](https://user-images.githubusercontent.com/2704742/44294287-a693d100-a262-11e8-9729-789208992221.png)

**Comment by Jared-Fogle** [comment]
![image](https://user-images.githubusercontent.com/35135081/44297893-08b5fb80-a28e-11e8-8b98-b8879f3e4600.png)
Can't seem to reproduce, there something I'm missing?

**Comment by avosirenfal** [comment]
No idea. Perhaps it's only those vents? That's the bathroom on the left side of Nexus on LV. Only the teal piece in my screenshot was visible, the entire vent system to the right was not.

**Comment by Jared-Fogle** [comment]
![image](https://user-images.githubusercontent.com/35135081/44297976-6d258a80-a28f-11e8-820c-734a47f73dde.png)
Strange, I still can't reproduce.

**Comment by avosirenfal** [comment]
Not sure, maybe it will happen to some other people.

**Comment by py01** [comment]
This was an issue on CM, happened a bunch.
https://gitlab.com/cmdevs/ColonialMarines/issues/3654
