### ISSUE TITLE
You can only spawn yourself in once via the player panel before it no longer puts you in the mob you spawn

### ISSUE THREAD

**Issue by Borisvanmemes** [ColonialMarines-Mirror/ColonialMarines-2018#148]
Title

**Comment by MrStonedOne** [comment]
This is an old bug /tg/ took like 3 years to finally fix themselves.

Somebody should find the /tg/ fix and port in it

**Comment by Ghommie** [comment]
You can manually change the Ckey of the mob you spawn to yours on the right click menu to control it. Shouldn't cause any issue or runtime. 

Aaaaaand I might have found the /tg/ fix to it in the player_panel.dm: 69th line.
`var ckey = key.toLowerCase().replace(/\[^a-z@0-9\]+/g,"");`
Other than that both files have little to no differences aside on the Job/roles possibilities and how the Job, Name, Real_Name and Key texts appear on the pop up interface. I guess.

**Comment by MrStonedOne** [comment]
Just find the issue on /tg/'s closed issues then you'll see the pr that fixed it.

**Comment by Ghommie** [comment]
Done that, I have found the solution to some peripherical problems but not the main one of this. 
It seems (at least to me) the old mob is not getting properly removed from the mob_list after the Dispose() act is called, Thus causing a lack of feedback and proceeding to give *no key* a new mob. 
The code for said feedback to be present, but they have different definitions for their garbage collection, deletes, and probably some older lists. Not my cup of tea.
