### ISSUE TITLE
Disabling darkness as ghost also disables other ghosts

### ISSUE THREAD

**Issue by Enzarel** [ColonialMarines-Mirror/ColonialMarines-2018#152]
What it says on the lid. Admins fix nao.

**Comment by Jared-Fogle** [comment]
This is an intentional feature of Bay-code, even though it sucks.

**Comment by Iatots** [comment]
Ye olde tg was like this too IIRC. Hopefully the fix can be ported relatively painlessly.

**Comment by Zostroll** [comment]
TG solved it by https://github.com/tgstation/tgstation/pull/8072 but according to CM coders it is intended. https://gitlab.com/cmdevs/ColonialMarines/issues/3047
