### ISSUE TITLE
Sidearm pouch doesnt carry all sidearms

### ISSUE THREAD

**Issue by Kingtrin** [ColonialMarines-Mirror/ColonialMarines-2018#157]
I noticed this when my sidearm pouch couldn't carry the m44. This is because the sidearm pouch has the line: can_hold = list("/obj/item/weapon/gun/pistol"). As a result items that make sense as sidearms will not fit if they have a different category (such as /obj/item/weapon/gun/revolver). 

There is the M276 belt designed to hold the m44 (under /obj/item/storage/belt/gun/m44) but nobodys going to use a belt slot for a fucking sidearm, nor is it good practice to exclude obvious sidearm weapons from the sidearm pouch. I suggest either A: The sidearm pouch is allowed to carry all items that we think of as sidearms or B: The sidearm pouch is renamed to the pistol pouch. The second option is not really ideal because the code makes few distinctions between revolvers and pistols, often referring to both interchangebly.

**Comment by JamesDenholm** [comment]
Given pouch/magazine/pistol can hold revolver speedloaders, I'm just gonna go ahead and make a PR that adds revolvers to pouch/pistol.
