### ISSUE TITLE
Guns are awful to use/special UI is awful to use/attachments & ammunition isn't well explained/special snowflake combat system

### ISSUE THREAD

**Issue by ghost** [ColonialMarines-Mirror/ColonialMarines-2018#16]
Revolvers require you to use the special UI to unload them (and to be loaded) because using them wields them.

Shotguns require you to use the special UI to pump them because using them wields them.

Special action is usually useless (sometimes just "clears the chamber"/discards a bullet you can't retrieve).

Toggle rail flashlight on the special UI is how you access scopes.

Underslung grenade launchers have a convenient UI button up the top left but used to require the special UI. I'm unaware if the under barrel shotguns & flamers have the better top left UI buttons.

Dual wielding (not regular wielding) has god awful accuracy negatives. That's not where the bullet goes but if it hits anything it crosses the tile of.

There's unexplained accuracy loss for moving and firing.

Attachments have a verbal description of how they affect your weapon but few really show off how badly/greatly they affect your weapon. For example the burst fire adapter does make you shoot two more bullets, which is easy to see. The stocks add wield delay, which is sometimes hard to recognise or comprehend what that means (is it ignore input for X seconds? It doesn't feel like *visually* wielding the weapon has a delay). Damage changes are not something you can understand, especially since aliens lack *visual* damage states. e.g. slap on a bayonet and a stock, do I have +5 or +40 melee damage? What was my starting melee damage? Who knows! """Accuracy""" is another one that's hard to recognise but bullet spread is easily recognisable. Gun size (or length as verbal feedback says) is an odd variable that might be redundant unless the shotgun getting bigger means it can't fit in a shotgun scabbard.

If I give an example of a verbal description and how it doesn't actually tell you anything:

>A rare stock distributed in small numbers to USCM forces. Compatible with the M41A, this stock reduces recoil and improves accuracy, but at a reduction to handling and agility. Seemingly a bit more effective in a brawl

Macros get around usage problems except for the hundred hotkeys SS13 already uses.

Ammunition differences are vague at best. e.g. shotgun flechette/buckshot/slug, 9mm versus 10x20 versus 10x24, holopoint, incendiary. Though that's another complaint about aliens lacking visual damage states.

**Comment by Borisvanmemes** [comment]
For duel wielding, not a bug, it's meant to be like that, also READ THE CM WIKI MAN, IT HAS MORE OR LESS EVERYTHING!

**Comment by KrabSpider** [comment]
Macros exist. The way to get around the clunky UI is by setting up a macro and forgetting it altogether. Thats practically it.
