### ISSUE TITLE
Can't pull items out of storages/containers that are bagged

### ISSUE THREAD

**Issue by ghost** [ColonialMarines-Mirror/ColonialMarines-2018#18]
Like medkits for example, you can't just drag open the inventory panel for the medkit from your bag and directly yoink any items out from it. Instead, you have to pull the medkit into your hand in order to use any items in it, which just clunky and awful.

**Comment by lolman360** [comment]
welcome to bay's SUPER HIGH RP-ALLOWANCE STORAGE SYSTEM
