### ISSUE TITLE
All synth names force default to david at roundstart

### ISSUE THREAD

**Issue by Kingtrin** [ColonialMarines-Mirror/ColonialMarines-2018#213]
and it makes me sad because I want to roleplay as a feweh alt, but nobody will believe me if my name is david. I also didn't see an interface option for gen1/2 so adding it in or making it more obvious would be helpful as well.

**Comment by Rohesie** [comment]
Fixed that here: https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/pull/200
