### ISSUE TITLE
Fix admin logs so they dont show every bullet being shot

### ISSUE THREAD

**Issue by DoctorPork** [ColonialMarines-Mirror/ColonialMarines-2018#24]
It's a cascading nightmare.

**Comment by CosmicScientist** [comment]
Dual wield SMGs you say?

**Comment by JJRcop** [comment]
https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/blob/fe26b64bc44add91c2a6f31422c94832148bd025/code/modules/projectiles/updated_projectiles/projectile.dm#L761-L773

remove the msg_admin_attack messages and msg_admin_ff

**Comment by iskyp** [comment]
[literally this](https://www.youtube.com/watch?v=nYibgPhqQhY)

**Comment by Rohesie** [comment]
There is a verb to toggle attacks and one to toggle FF.
