### ISSUE TITLE
Odd permastun when hit by tank tread

### ISSUE THREAD

**Issue by Kingtrin** [ColonialMarines-Mirror/ColonialMarines-2018#240]
A queen was seemingly permastunned by a tank tread while in the cockpit of the alamo. The stun lasted for at least several minutes, the queen was healthy (not sure if full health), and was on weeds. Where exactly the queen was stunned isn't clear but she ended up inside the cockpit and eventually killed. This was deemed a bug and the queen was given a free life by the admins. The xenos went on to eventually win the round. For some context the first time the queen got into the alamo and got stunned it was called up by the marines and not the queen. The tank was also in the shuttle at the same time.

This was the last round of the weekend tests we just had. I'm suprised nobody has made an issue because this seems like a pretty nasty bug. 

Edit: I assumed it was a tank shell causing the issue but other people are saying it was much more likely the tank treads are causing it, this issue was edited to reflect that.

**Comment by Rohesie** [comment]
https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/pull/246
