### ISSUE TITLE
Vendor and SMES UI are unusable

### ISSUE THREAD

**Issue by octareenroon91** [ColonialMarines-Mirror/ColonialMarines-2018#269]
For any machine that uses the modernized GUI, that GUI almost never loads on my machine (WINE, IE9).

**Comment by octareenroon91** [comment]
I can get tgui technically usable on my setup, so tgstation is "playable"
I can't even operate a vendor on this codebase.

**Comment by Supermichael777** [comment]
It would be interesting to see if you could trick BYOND into using a more compatable system.

Also try downgrading to IE 8 and test if possible, Microsoft fucked with how IE 9 Handles JS.
