### ISSUE TITLE
/tg/ logging port doesn't log hivemind.

### ISSUE THREAD

**Issue by subject217** [ColonialMarines-Mirror/ColonialMarines-2018#276]
@JJRcop 
I was told to ping you about this. Xeno hivemind should be in comms log or something of that sort, it isn't. Most xeno communications are through hivemind so it's rather important.

**Comment by JJRcop** [comment]
Argh! I missed that, fix coming soon

**Comment by JJRcop** [comment]
Hivemind is logged in game.log, but not in the individual logging panel. It's not as red alert as I thought, but still not good.
