### ISSUE TITLE
Revivable patients show up as braindead

### ISSUE THREAD

**Issue by Kingtrin** [ColonialMarines-Mirror/ColonialMarines-2018#296]
Happened today when a CMO was gunned down by a marine to 330 brute damage. Despite dying only a minute ago it showed a skull, but we could still use the defib. After much work we revived CMO to full health. I assume this happened due to the recent medical changes but I can't say for sure.

**Comment by Mark9013100** [comment]
Can confirm, all humans show up as un-revivable.

**Comment by Kingtrin** [comment]
Likely caused by #287 however looking at the code it makes no sense as to why the value for client was changed for all bodies. Previous uses of get_ghost, istype, and client worked as intended in the defib code.

**Comment by Surrealaser** [comment]
Threw up a fix here: https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/pull/300
