### ISSUE TITLE
Check-Antagonists permission not working correctly?

### ISSUE THREAD

**Issue by CosmicScientist** [ColonialMarines-Mirror/ColonialMarines-2018#297]
>Error: You do not have sufficient rights to do that. You require one of the following flags: +ADMIN.

I have access to the round status window. I assume I'm not supposed to given the message I get alongside it.

I have moderator rank/permissions.

**Comment by Supermichael777** [comment]
Whoever told these people it was acceptable to put anything on the same line as a control structure should be shot
