### ISSUE TITLE
TAZERS LAG THE SERVER TO HELL WHEN USED OH GOD [CRITICAL] [HELP]

### ISSUE THREAD

**Issue by F-OS** [ColonialMarines-Mirror/ColonialMarines-2018#309]
- [x] Is reproducible across multiple rounds

- [x] Can be reproduced by multiple people

steps:
1.taze someone
2. serb dies.

**Comment by Garen7** [comment]
copy paste the runtime

**Comment by F-OS** [comment]
we don't have a runtime yet i'm waiting on DMCA keyholders.
