### ISSUE TITLE
Some highlander issues

### ISSUE THREAD

**Issue by Kingtrin** [ColonialMarines-Mirror/ColonialMarines-2018#314]
You get spammed with claymores and compulsions of honor when the mode fires.
You can pick up the claymore without a compulsion of honor.
Firing the gamemode twice will give existing highlanders a second claymore.

Also the most important issue is that I cannot helicopter dick my claymore so quickly that it deflects all incoming fire. What is this shit a dumb meme or a real gamemode?

**Comment by factoryman942** [comment]
highlander button excludes poor benos who are stuck planetside

**Comment by Rohesie** [comment]
https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/pull/191
