### ISSUE TITLE
Shuttle stuck in transit after hijack

### ISSUE THREAD

**Issue by Kingtrin** [ColonialMarines-Mirror/ColonialMarines-2018#362]
We had a hijack go horribly wrong when the shuttle became stuck in transit and refused to crash. An attempt to fix the situation via admin intervention resulted in all of the xenos being gibbed and leaving only a corrupted queen alive. After the xenos got gibbed the shuttle proceeded to land (not crash) normally, with no gibs inside. This happened after testmerges were enabled, but with no obvious signs as to why this happened. I do not remember the map this was on. A hijack later in the day completed successfully.

**Comment by Ghommie** [comment]
This somehow remembers me of a goddamn awful similar bug CM had, which caused all the month's changes to get reverted for weeks... but at least this doesn't seem to happen every day.
