### ISSUE TITLE
Common chat when?

### ISSUE THREAD

**Issue by F-OS** [ColonialMarines-Mirror/ColonialMarines-2018#38]
Title. CM removed common radio chat and we need it back.

**Comment by CosmicScientist** [comment]
Good and bad. CM had a player count that made common chat intolerable and you had to limit ghost ears to not include radio because of this.

If tg talks as much as it does currently, a common chat wouldn't hurt.

**Comment by Rohesie** [comment]
https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/pull/348
