### ISSUE TITLE
RPL-Y powerloader sprite issue

### ISSUE THREAD

**Issue by Kingtrin** [ColonialMarines-Mirror/ColonialMarines-2018#407]
Sprites picked up by the new powerloader do not show up held by the loader, but the objects can still be manipulated as before. Purely visual as far as I can tell.

**Comment by Rohesie** [comment]
@Alterist

**Comment by Alterist** [comment]
I'm pretty sure that items don't show up held by the old powerloader sprite

**Comment by Rohesie** [comment]
Fixed in #411
