### ISSUE TITLE
Sprite License Issue?

### ISSUE THREAD

**Issue by callanrocks** [ColonialMarines-Mirror/ColonialMarines-2018#43]
Like half the sprites are still just /tg/station13 vanilla but some are edited or entirely original and there's no indication of what they're covered under.

As Oranges has pointed out, this is actually a problem.

Maybe start porting sprites over?

**Comment by Wilchenx** [comment]
pretty much, yes

**Comment by kyrahabattoir** [comment]
To be honest it's not just the sprites, it's any art assets added by the CM staff aswell: sounds, sprites, maps.

I'd argue that any writing and flavor texts is also technically part of the "content" rather than code.

**Comment by MrStonedOne** [comment]
the git history can be force pushed when needed.

Modified sprites or sprites based off of /tg/ sprites retain the cc-by-sa license. The same applies to sounds.

Wholly new assets could be an issue. It is the current stance of /tg/ that we have a good faith reason to believe that our source for the repo had the require agency to release the repo to us. If anybody who contributed an art asset to CM would like to contest that, they are suggest to write to mso@tgstation13.org. Good faith attempts to resolve such issues will be respected, Opening with a dmca to github or our ISP before attempting to communicate with us will not be considered a good faith attempt, and will be fought in court.

I should also remain anybody reading this that /tg/station13 Has a Registered DMCA Agent with the United States Copyright Office, and sending a dmca to any other entity may be in violation of the Digital Millennium Copyright Act (Ask your lawyer).

While maps may be seen as assets, in CM it looks like they are compiled in (by the map daemon), making them covered under gpl.

The way the compiler reads map files follows the same parsing rules as all DM code.

That being said, anybody who is the sole or primary map creator of an original CM map may contact me at the above email address to discuss removal.

**Comment by kyrahabattoir** [comment]
> Good faith attempts to resolve such issues will be respected, Opening with a dmca to github or our ISP before attempting to communicate with us will not be considered a good faith attempt, and will be fought in court.

**Comment by kyrahabattoir** [comment]
https://www.reddit.com/r/SS13/comments/94rz25/an_open_reply_to_mso_please_dont_use_the_work_i/

You got your discussion here.
