### ISSUE TITLE
Riot armor sprite is bugged

### ISSUE THREAD

**Issue by Kingtrin** [ColonialMarines-Mirror/ColonialMarines-2018#452]
Riot armor doesn't show up correctly when worn. It overrides the underlying clothing and shows the sprite as being naked. Seems to be a visual bug only.

**Comment by Ghommie** [comment]
Perhaps, which riot armor? I'd assume the normal one, and not the mil-pol's one, but I can't be sure.
It's simply a visual bug caused by a lack of sprite and the visual flags removing the underlays.
