### ISSUE TITLE
Players with xeno preferences enabled are treated as having them turned off

### ISSUE THREAD

**Issue by drawsstuff** [ColonialMarines-Mirror/ColonialMarines-2018#467]
It's been happening for a few days now. You dont get round start xeno, 5 rounds in a row. You think "huh, that's odd". What's even stranger is when you dont ever get picked for hatching xenos. Then you notice something. Despite you being the very last ghost with xeno on, or the very last ghost in general, the larva start burrowing, even thought you have it on.

This doesnt just cuck you out of early xenos. It makes you wait until every single ghost gets to go before you. You wait 30 minutes to be stuck with a t1 for the rest of the game. 

How is that fun?

https://i.imgur.com/ia3sDVq.png

**Comment by Rohesie** [comment]
This only applies to non-deadmined staff.
