### ISSUE TITLE
Corrupted xenos know english but cant speak it

### ISSUE THREAD

**Issue by Kingtrin** [ColonialMarines-Mirror/ColonialMarines-2018#476]
Being added to the corrupted hivemind, by default, gives you the english language. The issue is that in 
 /mob/living/carbon/xenomorph/say.dm the code seems to override any other languages the xenos might know in favor of xenocommon. Removing xenocommon still doesn't let you speak english as it then goes all the way down to hivemind, skipping the section intended for english, forcing you to speak hivemind even without a prefix. There are multiple breaks early on so that probably has something to do with why its not going through.

This is annoying because doing events which involve xenos and humans talking is a serious pain.

**Comment by Ghommie** [comment]
Have you tried using the :0 (or whatever it was for English/Galactic Common) prefix before speaking? I read that part of the code and theorically it forces the xenomorph to speak xeno common if a prefix isn't used.

**Comment by Kingtrin** [comment]
Yes, i tested every combination and it ignores prefix keys. it's basically forcing you to say .x before anything else.
