### ISSUE TITLE
SL vendor lists HEDP, gives out HIDP

### ISSUE THREAD

**Issue by CosmicScientist** [ColonialMarines-Mirror/ColonialMarines-2018#541]
>The HEDP grenades in the SL vendor give out HIDP instead

Taken from an ahelp:
[marine_vending.dm#L493](https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/blob/master/code/game/machinery/vending/marine_vending.dm#L493)
Can't see anything but smoke grenades in there so I'm not entirely sure what they were on about. Couldn't figure out who originally ahelped but hopefully they'll make a github account for the next bug to explain better.

**Comment by factoryman942** [comment]
that's old vendors, point ones have the issue:
https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/blob/master/code/game/machinery/vending/new_marine_vendors.dm#L982
