### ISSUE TITLE
Dylovene pills are empty

### ISSUE THREAD

**Issue by Anonmare** [ColonialMarines-Mirror/ColonialMarines-2018#587]
I'm not talking about the pill bottles, the _actual pills_ are empty, they have no reagents in them. According to Francinium, they have an undefined path.

CosmicScientist and Francinium can confirm.

**Comment by CosmicScientist** [comment]
#589 half fixes this issue (offending PR mentioned there too). Dylovene pill bottles use anti-tox pills which are undeclared in the code whilst dylovene pills are fully functional if the reagent works as intended.
