### ISSUE TITLE
Shotgun loading rig bug/glitch

### ISSUE THREAD

**Issue by Ryder5** [ColonialMarines-Mirror/ColonialMarines-2018#760]
Fill a shotgun shell rig full, then take one hand full out, then refill using a shotgun shell BOX. It will cause the shotgun rig to hold more shotgun shells than it is suppose to be able to hold. I know it works with slugs, not sure about flechettes, and buckshot. I will try to take screenshots of this happening soon.

**Comment by Rohesie** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps
