### ISSUE TITLE
Double barrel shotgun Ammo HUD bug/glitch

### ISSUE THREAD

**Issue by Ryder5** [ColonialMarines-Mirror/ColonialMarines-2018#761]
When the double barrel shotgun is loaded with slugs the ammo HUD shows a green shell not a red shell, Not sure if this is the same with flechettes as well. I will try to take screenshots of this happening.

**Comment by Rohesie** [comment]
The repo has moved to https://github.com/tgstation/TerraGov-Marine-Corps
