### ISSUE TITLE
Replace the stupid slot in, slot out, recharge, repeat engine

### ISSUE THREAD

**Issue by ChiropterousHoarder** [ColonialMarines-Mirror/ColonialMarines-2018#80]
It's boring as hell and provides zero engaging gameplay for ship engineers and should be replaced with something like the hell crystal.

**Comment by mrturkeytoe** [comment]
Concept of gas? It's not like they removed it, atmos still works just as it always has there's just no gas cans available to people I'm pretty sure.

**Comment by F-OS** [comment]
@mrturkeytoe gas is literally purposefully broken and turned off by CM coders.
