### ISSUE TITLE
medicine reagents don't work

### ISSUE THREAD

**Issue by factoryman942** [ColonialMarines-Mirror/ColonialMarines-2018#9]
they don't heal over time
iirc area meds (trauma/burn kits / bandages/gauze) should also give heal over time, but don't

**Comment by Rohesie** [comment]
Advanced kits and bandages/gauze heal a single amount, not over time.
Gauze and trauma kits also are used to stop bleeding and cleaning the wound due to infections.

What else doesn't heal over time?
